Adds an email message that is sent when an order is refunded.
mitodl/mitxonline pull request #1000
Opened 2022-09-16 18:02 UTC by jkachel

#### Pre-Flight checklist

- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested

#### What are the relevant tickets?

Fixes #957

#### What's this PR do?

Adds a new email message that gets sent when an order is refunded. The text of the messages is in the issue (#957). 

#### How should this be manually tested?

Automated tests should work.

The easiest way to trigger the refund is through a Django shell; this method does not require that your system be able to accept callbacks from CyberSource. (Refunding through the Django Admin does attempt to perform the refund through CyberSource.) 

From a shell, load a FulfilledOrder, then call the "refund" method:
```
from ecommerce.models import FulfilledOrder

order = FulfilledOrder.objects.first()

response_data = { "id": "an id" } # the only required field here is id 

order.refund(api_response_data=response_data, amount="50", reason="testing")
```
This should trigger the email. Note that this will change the status of the order in the system. 

If your system can receive callbacks from CyberSource, you can post a refund through the EBC. That should also trigger the refund email.

2022-09-19 15:29 UTC, asadali145 requested changes
Overall LGTM! A minor change in calling celery task is required.

2022-09-19 15:29 UTC, asadali145 commented on ecommerce/models.py
> +        send_order_refund_email(self.id)
I think you missed calling this celery task using `.delay()`.

2022-09-19 15:29 UTC, asadali145 commented on ecommerce/mail_api.py
> +    try:
I think we should start this `try` block before the context manager. The following 3 lines won't seem to be troubling.

2022-09-19 15:29 UTC, asadali145 commented on ecommerce/templates/mail/order_refund_message/subject.txt
> +Refund of MITxOnline Order
Can we add the order number in the subject as it is mentioned in the ticket?

2022-09-19 18:40 UTC, jkachel commented
https://github.com/mitodl/mitxonline/pull/1000/commits/19f9284af4af217fbba646972b5adedc7601ec8c should have the requested changes.

2022-09-20 05:57 UTC, asadali145 approved these changes
Looks Great!

2022-09-20 13:59 UTC, merged