Save users with no enrollment into file
mitodl/mitxonline pull request #1096
Opened 2022-10-05 19:46 UTC by annagav

#### What are the relevant tickets?
None

#### What's this PR do?
Update the management command `upgrade_eligible_users` to save users that are not currently enrolled in mitxonline, so that they can receive coupons.

#### How should this be manually tested?
The input file should look something like:
```
useremail@example.com,course-v1:MITxT+14.310x+3T2022
```
To test this PR you would need an existing using in your local instance but not enrolled in this course. The you
run the command `./manage.py upgrade_eligible_users <file_name.csv>`.
It should create a file with your record that is missing the enrollment.

2022-10-05 20:55 UTC, jkachel requested changes
Small change for IDs but otherwise looks OK.

2022-10-05 20:55 UTC, jkachel commented on courses/management/commands/upgrade_eligible_users.py
> +                    users_no_enrollment.append((row[0], course_run.course_id))
This should be the `courseware_id` for the course run - if it's numeric the `generate_legacy_enrollment_codes` command will look it up in the MicroMasters import CourseId table, but it'll look it up based on the MicroMasters ID so coupon generation later will fail. Using the readable ID for the run will work, though.

2022-10-06 14:33 UTC, annagav commented
@jkachel I addressed your comment. Thanks for the review!

2022-10-06 17:48 UTC, jkachel approved these changes
LGTM 👍

2022-10-06 19:16 UTC, merged