Added Wagtail and initial model definitions
mitodl/mitxonline pull request #11
Opened 2021-07-14 20:26 UTC by gsidebo

#### Pre-Flight checklist

- [x] Migrations
  - [x] Migration is backwards-compatible with current production code
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested
- [x] Settings
  - [x] New settings are documented and present in `app.json`
  - [x] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
N/A

#### What's this PR do?
Adds Wagtail, defines some barebones initial models, and a template tag to allow us to serve Wagtail images without using the Wagtail image view

#### How should this be manually tested?
(Required)

#### Any background context you want to provide?
(Optional)

2021-07-15 14:11 UTC, rhysyngsun requested changes
A few small things on the code, how should i go about testing this?

2021-07-15 17:01 UTC, gsidebo commented
@rhysyngsun Just added testing steps

2021-07-15 18:47 UTC, rhysyngsun commented on README.md
> +  to `edx.odl.local`. Your `/etc/hosts` entry should look like this:
well this one was embarassingly wrong

2021-07-15 21:12 UTC, rhysyngsun requested changes
One issue but i think otherwise it's looking good

2021-07-15 21:12 UTC, rhysyngsun commented on main/views.py
> +    return redirect_to_login(reverse("wagtailadmin_home"), login_url="/signin")
`reverse()` isn't imported so this is throwing an error, it could probably use a test too.

2021-07-16 16:06 UTC, rhysyngsun approved these changes

2021-07-16 18:38 UTC, merged