asadiqbal08/Move prerequisites
mitodl/mitxonline pull request #126
Opened 2021-08-26 11:42 UTC by asadiqbal08

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots

#### What are the relevant tickets?
fixes: #125
fixes: #137 

https://projects.invisionapp.com/share/RN11DSJOGXFD#/screens/455477372_Course_Detail

#### What's this PR do?
Move the prerequisites area in page.

#### Screenshots (if appropriate)
![screencapture-localhost-8013-cms-pages-10-edit-preview-2021-09-03-16_29_53](https://user-images.githubusercontent.com/7334669/131998817-d4b745aa-6f9c-4bef-8c41-982355a009a7.png)

![screencapture-localhost-8013-cms-pages-10-edit-preview-2021-09-03-16_46_44](https://user-images.githubusercontent.com/7334669/132000737-03c4164c-b392-406c-a45b-28dc131f37ef.png)

2021-08-30 17:11 UTC, pdpinch commented
Can I get a larger screenshot of the desktop view, which includes the 4 pieces of metada, "start date", "length" "effort", and "price" ?

What happened to "price" in the mobile screenshot?

2021-08-31 12:15 UTC, arslanashraf7 requested changes
I requested a small change. Also, it would be a good idea to rebase this PR because:

- Another PR was merged which did few tweaks to the product page as well
- The [Invision Design](https://projects.invisionapp.com/share/RN11DSJOGXFD#/screens/455477372_Course_Detail) attached to the PR has more spacing on the headers.

Doing the above might save us some regression issues.

2021-08-31 12:15 UTC, arslanashraf7 commented on cms/templates/product_page.html
> +              <p>{{ page.prerequisites |richtext }}</p>
We don't need to use an external paragraph element, the `richtext` tag automatically adds the external `<p>` tag for the whole content.
```suggestion
              {{ page.prerequisites |richtext }}
```

2021-09-01 11:31 UTC, asadiqbal08 commented
@pdpinch kindly take a look and let me know do you require to modify something in design with the tiles or ok with that ? 


![screencapture-localhost-8013-cms-pages-10-edit-preview-2021-09-01-16_30_57](https://user-images.githubusercontent.com/7334669/131664061-16dec4cd-42fa-4dcd-ad00-7270beef8bb6.png)



![screencapture-localhost-8013-cms-pages-10-edit-preview-2021-09-01-16_30_39](https://user-images.githubusercontent.com/7334669/131664022-20c86f3f-7083-46a5-b56b-e3bf84e5efd9.png)

2021-09-01 12:13 UTC, arslanashraf7 commented
@asadiqbal08 I believe there is a notable difference in the spacing of the titles. Can you verify them with the [Invision Link](https://projects.invisionapp.com/share/RN11DSJOGXFD#/screens/455477372_Course_Detail)? You might also need to verify the spacing for the mobile screen. I'm attaching the screenshot from the invasion desktop design below:
<img width="520" alt="Screenshot 2021-09-01 at 5 10 13 PM" src="https://user-images.githubusercontent.com/34372316/131669051-d3ec6cc8-a4c1-4218-bf88-a17246e0491e.png">

2021-09-01 12:31 UTC, pdpinch commented
A couple things:

- Arslan's screenshot definitely looks wrong. I'm not sure why it's different from yours.  
- The designer just updated the screens to standardize the background and make the info cards (start date/length/effort/price) stand out more. Can you add those changes to this PR?
- Can you also fix this bug: #137

2021-09-01 12:39 UTC, pdpinch commented
And one more thing:

4. Please move Prerequisites down, below "What you'll learn" and above "Meet your Instructors." I'll add a comment on InVision to do that as well.

2021-09-01 12:48 UTC, arslanashraf7 commented on cms/templates/product_page.html
> +            {% endif %}
@asadiqbal08 I believe you need to rebase on main as I mentioned in my earlier comment on the PR, Wagtail already wraps the rich text in an external parent `<p` tag and I've removed the extra `<p` tags in one of my PRs. https://github.com/mitodl/mitxonline/pull/98/files.

2021-09-03 12:32 UTC, asadiqbal08 commented
@pdpinch I have updated the Screenshots in the description of the PR. Please take a look and let me know.

2021-09-03 12:49 UTC, pdpinch commented
Screenshots look good. 

I think there's some overlap between this PR and https://github.com/mitodl/mitxonline/pull/146#pullrequestreview-745955300 -- please coordinate with @Wassaf-Shahzad so we avoid any regressions.

2021-09-03 12:49 UTC, pdpinch approved these changes

2021-09-03 15:15 UTC, arslanashraf7 approved these changes
Looks good 👍. One last minor comment, Feel free to merge after that.

- Since you changed property color to white, Can you remove the background color from the product detail page https://github.com/mitodl/mitxonline/blob/main/static/scss/product-details.scss#L4 as well, so that the product detail page has a design specific grey background.

2021-09-07 07:32 UTC, merged