Program Drawer: remove enroll button
mitodl/mitxonline pull request #1314
Opened 2022-12-22 18:35 UTC by annagav

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots

#### What are the relevant tickets?
Fix https://github.com/mitodl/mitxonline/issues/1309
#### What's this PR do?
remove enroll button and financial aid assistance from the program drawer

#### How should this be manually tested?
Go to user dashboard, open the program drawer and check that courses that you not enrolled in do not show enroll button.
<img width="833" alt="Screen Shot 2022-12-22 at 1 31 27 PM" src="https://user-images.githubusercontent.com/7574259/209203404-344cffbd-1511-41ab-bd7d-5c36bacb03a7.png">

2022-12-23 14:04 UTC, jkachel requested changes
Functionality looks good but I think we want to hide the entire Enroll section?

2023-01-09 15:23 UTC, annagav commented
@jkachel this is ready for your review. Thanks

2023-01-09 19:28 UTC, jkachel approved these changes
Very small change and then this should be good to go

2023-01-09 19:28 UTC, jkachel commented on frontend/public/src/components/ProgramCourseInfoCard.js
> -        <div className="row flex-grow-1 pt-3">
Bit too much - the row and column need to stick around or the course image looks weird:
![image](https://user-images.githubusercontent.com/945611/211391099-ea432d75-3068-4907-a82a-32d1705085f9.png)
The top card has the row and the column but nothing in it.

2023-01-09 21:21 UTC, merged