refactor!: Remove `Course.position_in_program`
mitodl/mitxonline pull request #1429
Opened 2023-02-14 06:31 UTC by asadali145

#### Pre-Flight checklist

- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fixes https://github.com/mitodl/mitxonline/issues/1220

#### What's this PR do?
Removes `Course.position_in_program` and `Course.program` fields.

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

2023-02-23 13:30 UTC, jkachel requested changes
One thing I noticed: the `configure_instance` command needs a small update to not specify `position_in_program`. Otherwise, seems to work OK for me 👍

2023-02-23 16:06 UTC, rhysyngsun reviewed
Generally LGTM, although could you remove the references to `--program-position` in `docs/source/commands/create_courseware.rst`?

2023-02-28 16:55 UTC, jkachel requested changes
I'm getting a test failure in `courses/serializers_test.py::test_serialize_program[False]`. Functionality looks OK though and `configure_instance` works now too.

2023-03-06 10:22 UTC, asadali145 commented
@jkachel OR @rhysyngsun Could you guys please have one final look and approve this? We will merge this PR and will create follow up Tickets/PR for the removal of `Course.program`.

2023-03-06 13:07 UTC, asadali145 commented on courses/serializers.py
> -class ProgramEnrollmentSerializer(serializers.ModelSerializer):
It was unused.

2023-03-06 13:10 UTC, jkachel approved these changes
Looks OK to me. I'm not sure why the `ProgramEnrollmentSerializer` is being removed but I'm not necessarily opposed to it being removed.

2023-03-06 18:27 UTC, rhysyngsun commented on courses/serializers.py
> -class ProgramEnrollmentSerializer(serializers.ModelSerializer):
Makes sense, we shouldn't have unused code like that and if we want it back it's easy enough to bring back from git history.

2023-03-07 10:15 UTC, merged