Order History table makeover
mitodl/mitxonline pull request #1535
Opened 2023-04-06 16:42 UTC by annagav

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
#### What are the relevant tickets?
Fix https://github.com/mitodl/hq/issues/718

#### What's this PR do?
Updates the order history page to display a proper table so that screen readers work.

#### How should this be manually tested?
Go to orders history page. Make sure it looks good. Then use a screed reader to go over the order history structure.

<img width="1239" alt="Screen Shot 2023-04-06 at 12 34 16 PM" src="https://user-images.githubusercontent.com/7574259/230442724-3feb901b-c955-4a4e-9764-6da4063e10c4.png">

2023-04-10 15:09 UTC, collinpreston requested changes
I am able to use the screen reader to access and hear the table, columns, and rows.  However, there are a couple of issues introduced:
1. The mobile view of the order history page needs refactoring.
2. The "view" link in the far right column is not accessible with the tab key.  I think this requires `role="link"`
3. It might be helpful to add `title` to the table and reference the `h1` header "Order History"

2023-04-14 15:48 UTC, collinpreston commented on frontend/public/src/containers/pages/checkout/OrderHistory.js
> +                      <td /> <td /> <td />
I think these are causing an error to be thrown to the console in Google Chrome: `Whitespace text nodes cannot appear as a child of <tr>. Make sure you don't have any extra whitespace between tags on each line of your source code.`

2023-04-20 12:56 UTC, annagav commented
@collinpreston this is ready for another review, thanks!

2023-04-20 20:12 UTC, collinpreston requested changes
Looks good, I would just add an aria label to the "View" link for each item in the table.  Something like "View order for {item}" would then be spoken like "View order for E2E Test Course link" for those using screen readers.  Everything else looks good!

2023-04-20 23:03 UTC, collinpreston approved these changes
Nice, I _think_ that additional aria-label will be helpful for those who need it.  Looks good!

2023-04-21 09:41 UTC, merged