Pull courserun title, dates from studio
mitodl/mitxonline pull request #166
Opened 2021-09-09 09:29 UTC by umarmughal824

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

2021-09-10 16:55 UTC, rhysyngsun commented
If the title is always going to be pulled from openedx, then we should make it readonly in the django admin and put some help text in there noting this.

2021-09-13 12:51 UTC, umarmughal824 commented
> If the title is always going to be pulled from openedx, then we should make it readonly in the django admin and put some help text in there noting this.

@pdpinch what's your opinion on that?

2021-09-13 21:03 UTC, gsidebo commented
If nothing else, I think it would be good to leave the title field alone for local development. It's helpful just to be able to create/update courses locally no matter if they have equivalents in edX or not. I think the only thing we'd be protecting against by setting it to read-only would be a mistaken edit in Django admin et al, which I'd consider an unlikely event, and it wouldn't even make much of a difference in the app since we use the `CoursePage` title, not the `Course` title, in the product detail page

2021-09-13 21:17 UTC, gsidebo requested changes
Just a few very minor suggestions

2021-09-13 21:17 UTC, gsidebo commented on main/settings.py
> +    default=None,
```suggestion
    default="*",
```

If we're defaulting this to run once every day, why not make `"*"` the actual default value for the setting? If you do this, you can replace `CRON_COURSERUN_SYNC_DAYS or "*"` with just `CRON_COURSERUN_SYNC_DAYS`

2021-09-13 21:17 UTC, gsidebo commented on main/settings.py
> +    description="'day_of_week' value for 'sync-courseruns-data' scheduled task (default will run once a day).",
```suggestion
    description="'day_of_week' value for scheduled task to sync course run data (by default, it will run each day of the week).",
```

2021-09-13 21:17 UTC, gsidebo commented on main/settings.py
> +    description="'hours' value for the 'sync-courseruns-data' scheduled task (defaults to midnight)",
```suggestion
    description="'hours' value for scheduled task to sync course run data (by default, it will run at midnight)",
```

2021-09-14 01:36 UTC, pdpinch commented
>>  If the title is always going to be pulled from openedx, then we should make it readonly in the django admin and put some help text in there noting this.

> @pdpinch what's your opinion on that?

There's a case where the title isn't pulled from open edX, and that's when the course exists in the catalog, but not yet on open edX. This could happen when we choose to start marketing a course before dates have been chosen. 

I think the help text is a good idea -- esp. if it's not too hard to mention the update the schedule. But I disagree with making it read-only.

2021-09-14 08:04 UTC, umarmughal824 commented
> If nothing else, I think it would be good to leave the title field alone for local development. It's helpful just to be able to create/update courses locally no matter if they have equivalents in edX or not. I think the only thing we'd be protecting against by setting it to read-only would be a mistaken edit in Django admin et al, which I'd consider an unlikely event, and it wouldn't even make much of a difference in the app since we use the `CoursePage` title, not the `Course` title, in the product detail page

I had the pretty much same feeling because everytime we require some changes in the title we will have to go to shell and then edit it. For us (developers) it's not an issue but for the marketing team or so, they will feel it tedious work.

2021-09-14 08:11 UTC, umarmughal824 commented
> > > If the title is always going to be pulled from openedx, then we should make it readonly in the django admin and put some help text in there noting this.
> 
> > @pdpinch what's your opinion on that?
> 
> There's a case where the title isn't pulled from open edX, and that's when the course exists in the catalog, but not yet on open edX. This could happen when we choose to start marketing a course before dates have been chosen.
> 
> I think the help text is a good idea -- esp. if it's not too hard to mention the update the schedule. But I disagree with making it read-only.

In my opinion, in that case we should provide help_text for all the fields (title and dates) and I would put up a separate PR for that.

2021-09-14 13:26 UTC, gsidebo approved these changes
Looks good! 👍

2021-09-15 05:52 UTC, merged