Fix program id retrieval when sharing
mitodl/mitxonline pull request #2061
Opened 2024-01-16 20:39 UTC by annagav

### What are the relevant tickets?
Fix https://github.com/mitodl/mitxonline/issues/2056

### Description (What does it do?)
Fixes a bug when getting the program id.

### How can this be tested?
Go to view your program record, click enable sharing, check that sharing request was called with the correct program id.

<img width="833" alt="Screenshot 2024-01-16 at 3 37 15 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/9b162af5-6ccb-45b5-a531-b8cf60e29bf4">

2024-01-19 13:14 UTC, annagav commented on frontend/public/src/containers/pages/records/LearnerRecordsPage.js
>    getOnlyProgramId() {
I also has that question. I think the getOnlyProgramId does the same thing getProgramId without the check for `return this.props.match.params.program.length !== 36`. But we should ask @jkachel for the meaning behind it.

2024-01-19 16:25 UTC, jkachel commented on frontend/public/src/containers/pages/records/LearnerRecordsPage.js
>    getOnlyProgramId() {
The URLs are the same if you're viewing for a program or a shared record. The shared records use a UUID, hence 36. Neither of these two functions are named particularly well; `getProgramId` is really a check for a shared program record where `getOnlyProgramId` only returns if there's a program ID (aka an int).

2024-01-19 16:55 UTC, jkachel requested changes
Functionality works well but I think these two functions should be renamed to something more representative of what they do. These should only be used here so that should be a quick refactor.

2024-01-19 21:08 UTC, collinpreston requested changes
So I have a program with 2 required courses.  I also have a program certificate.  When I load the program record page I am seeing an error in the console and the program sharing buttons are not displayed.  When I switch back to the main branch, this does not occur.

2024-01-19 22:32 UTC, collinpreston approved these changes
Very good!

2024-01-23 14:36 UTC, jkachel approved these changes
LGTM 👍

2024-01-23 16:34 UTC, merged