Catalog Update without having to hit bottom of page
mitodl/mitxonline pull request #2076
Opened 2024-01-30 20:29 UTC by JenniWhitman

### What are the relevant tickets?
fixes https://github.com/mitodl/hq/issues/3141
fixes https://github.com/mitodl/hq/issues/2992
fixes https://github.com/mitodl/hq/issues/2910
fixes https://github.com/mitodl/hq/issues/2909

### Description (What does it do?)
Rather than relying on the page scroll to load more, there is a chain of requests to fill out the data for the page until it is full, regardless of page movement, once the initial load is complete.

### How can this be tested?
Set up data with more than 12 courses and/or programs (ideally both). You will want a few departments loaded as well.  Load the catalog and click to filter the list.  You should get all cards loading in.

2024-02-12 18:25 UTC, annagav requested changes
Few minor comments and failing js tests.

2024-02-12 18:25 UTC, annagav commented on frontend/public/src/containers/pages/CatalogPage.js
> +    console.log("gets here")
let's remove this line

2024-02-12 18:25 UTC, annagav commented on frontend/public/src/containers/pages/CatalogPage.js
> +        console.log(response)
and this one

2024-02-12 18:25 UTC, annagav commented on frontend/public/src/containers/pages/CatalogPage.js
> +  async loadMorePrograms() {
is this needed?

2024-02-13 14:03 UTC, annagav commented
It says the page is unresponsive.
<img width="1524" alt="Screenshot 2024-02-13 at 9 02 17 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/bef9f290-2f74-4624-85a4-d4f79958ead8">

2024-03-20 13:43 UTC, JenniWhitman commented
Closing as this was fixed in https://github.com/mitodl/mitxonline/pull/2130

2024-03-20 13:43 UTC, closed without merging