Upgrade dialog choose any course run
mitodl/mitxonline pull request #2124
Opened 2024-03-08 21:30 UTC by annagav

### What are the relevant tickets?
Fix https://github.com/mitodl/hq/issues/3671 and partially https://github.com/mitodl/hq/issues/3109

### Description (What does it do?)
Changes the enroll now button to open the dialog whever there is more then one course run available for enrollment.
In the dialog the dropdown select course run shows all enrollable course runs.
If the course is upgradable then:
1. the button to enroll is enabled
2. the course run has a label (can upgrade)
3. The payment info is displayed.

### Screenshots (if appropriate):
<img width="747" alt="Screenshot 2024-03-08 at 4 19 55 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/4fdbb98a-cf8f-4e75-94cf-0471de6747e1">

<img width="746" alt="Screenshot 2024-03-08 at 4 20 06 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/44fd4f93-a4b6-4482-bb63-93717f1d82bf">

### How can this be tested?
There are few scenarios to test:
1. All course runs for a given course don't have products but are enrollable
2. One course run has product and other not, but both are enrollable
3. two course runs both have products both are enrollable, but only one is upgradable (meaning payment_deadline is in the future)

2024-03-11 17:59 UTC, pdpinch commented on frontend/public/src/components/CourseProductDetailEnroll.js
> +                selected={run.id === elem.id}
Can we remove the default selection & force the user to make a choice?

2024-03-12 13:15 UTC, annagav commented
If we want to have the select, not having something selected by default it would look something like this:

<img width="748" alt="Screenshot 2024-03-12 at 9 13 42 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/7d822c82-190f-44e7-8a88-21b8b34eb90d">

2024-03-12 18:29 UTC, annagav commented
We could try to add a default "nothing selected" option. And then we would need to disalbe all the buttons in the dialog:

<img width="745" alt="Screenshot 2024-03-12 at 2 28 50 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/9ff96a40-37b8-4f36-877a-da916430c3cb">

2024-03-12 19:05 UTC, pdpinch commented
@annagav this works for me, but I'd like to tweak the "nothing selected" text to be something based on best practices. 

@mbilalmughal can you weigh in on this? 

Some context: customer support has brought up that we get a number of tickets from learners who enroll without realizing what course dates they are signing up for. CS would like to cut down on these tickets and they have suggested that we **not** provide a default course run in situations when there are multiple runs like this. Learners would be required to make an active choice between the runs. 

In the past, I had been reluctant to make this change, since it adds friction to the enrollment process, but now that I've seen the frustration it is causing customer support, I'm willing to try something like this.

2024-03-13 12:17 UTC, pdpinch commented
I think this will address https://github.com/mitodl/hq/issues/3400 as well.

2024-03-13 13:12 UTC, annagav commented
@mbilalmughal Thanks for the feedback. The only thing is that when the run is not selected we can't show the price and certificate availability info since it depends on the run selected. So it would look a bit different on my screenshots.

2024-03-13 13:56 UTC, Ferdi commented
Perhaps just make the date field required ?

I don't think users will understand "can upgrade". What is that supposed to do ?

2024-03-13 14:42 UTC, annagav commented
> Perhaps just make the date field required ?
> 
> I don't think users will understand "can upgrade". What is that supposed to do ?

We are trying to mark courses that could be upgraded for a certificate track. What wording do you think would be better?

2024-03-13 17:05 UTC, pdpinch commented
Instead of marking the ones that can be upgraded with `(can upgrade)`, we can mark the ones that can't be upgraded with `(no certificate available)` -- which matches the text in the info box when there is no certificate.

2024-03-13 18:28 UTC, pdpinch commented
> For the same course, you can upgrade for some runs but other runs ? I did't know that was the case
> 
This shouldn't happen, but we've had edge cases where the course team has left enrollment open in one of the runs after the course upgrade deadline. This is what happened with https://github.com/mitodl/hq/issues/3671

2024-03-14 03:11 UTC, annagav commented
Latest screenshots:

<img width="748" alt="Screenshot 2024-03-13 at 9 24 34 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/0f653627-05ca-4957-b909-a446b1f0e1b0">
<img width="746" alt="Screenshot 2024-03-13 at 9 24 56 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/619e17f3-b908-40a6-8ee5-600328399a49">

2024-03-18 12:14 UTC, annagav commented
@pdpinch @mbilalmughal could you review the latest screenshots?

2024-03-18 14:51 UTC, pdpinch commented on frontend/public/src/components/CourseProductDetailEnroll.js
> +            Nothing Selected
```suggestion
            Please Select
```

2024-03-18 16:58 UTC, annagav commented
@collinpreston this is ready for review now.

2024-03-20 00:17 UTC, collinpreston requested changes
Can you write what is expected for each of the test cases listed in the PR description?

2024-03-20 00:23 UTC, collinpreston commented on frontend/public/src/components/CourseProductDetailEnroll_test.js
> +        assert.isTrue(selectorControlItems.at(0).text() === "Nothing Selected")
This should be updated.

2024-03-20 00:33 UTC, collinpreston commented
@pdpinch just my opinion, but feels a bit confusing to have the disabled "Enroll and pay" button.  I don't think it's natural to identify that the "Enroll for free" link is what should be clicked on.

2024-03-20 01:42 UTC, pdpinch commented
> I don't think it's natural to identify that the "Enroll for free" link is what should be clicked on when a course does not offer an upgraded enrollment.

What are our options?

@mbilalmughal what do you think?

2024-03-20 17:03 UTC, mbilalmughal commented
> > I don't think it's natural to identify that the "Enroll for free" link is what should be clicked on when a course does not offer an upgraded enrollment.
> 
> What are our options?
> 
> @mbilalmughal what do you think?

I agree with @collinpreston. It doesn't make sense to disable it.
@pdpinch if you remember, we added the disabled button state just to ensure the user selects the date first. Nothing else is required. If you are okay with it, let's remove the disabled button state.

2024-03-20 18:21 UTC, annagav commented
@collinpreston If there is no upgradable run the dialog should look like this: 
<img width="746" alt="Screenshot 2024-03-20 at 2 19 36 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/44252fa4-9f82-4c3d-9bd4-b27dab5f244e">

We could remove the "without certificate" part.

2024-03-20 18:46 UTC, annagav commented
@collinpreston I updated the description with test scenarios and corresponding pictures.

2024-03-21 14:31 UTC, collinpreston requested changes
Looks good.  Just a documentation request.

2024-03-21 14:31 UTC, collinpreston commented on frontend/public/src/components/CourseProductDetailEnroll_test.js
> +  it(`renders enrollment dialog for a course with multiple non-upgradable active runs`, async () => {
Can you update the description of this test, and the one above that you modified, to indicate what the test is ensuring happens?

2024-03-21 15:00 UTC, collinpreston approved these changes
Looks good.  I wouldn't merge until we get a decision from Peter/Bilal regarding the UX/UI of the disabled button.

2024-03-21 15:24 UTC, merged

2024-03-21 15:24 UTC, pdpinch reviewed
Let's merge this and get in onto RC so I can try it out with (semi-)real courses.