Add course format info
mitodl/mitxonline pull request #2175
Opened 2024-04-23 18:50 UTC by annagav

### What are the relevant tickets?
related to https://github.com/mitodl/hq/issues/2833

### Description (What does it do?)
Updates the design of the course info box

### Screenshots (if appropriate):

<img width="377" alt="Screenshot 2024-04-23 at 2 50 08 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/0ef90d88-db23-4d25-b6db-d1ac826b4d4e">

2024-04-29 12:54 UTC, mbilalmughal commented
@annagav I would like to point out a few minor alignment issues. It would be great if you could fix these, it will be pixel perfect then.

![image-1](https://github.com/mitodl/mitxonline/assets/7486671/d86b169c-b9d3-4ef3-bed3-948a31aa9ff9)

![image-2](https://github.com/mitodl/mitxonline/assets/7486671/9d1f92b9-128c-45da-9817-1806de59b4a6)

![image-3](https://github.com/mitodl/mitxonline/assets/7486671/c7d7ad93-7108-4240-beb4-3f6313bb82fb)

Let me know if you need any help 👍

2024-04-29 13:15 UTC, collinpreston requested changes

2024-04-29 13:15 UTC, collinpreston commented on frontend/public/scss/product-page/product-details.scss
> +            }
Is this required?

2024-04-29 13:15 UTC, collinpreston commented on frontend/public/scss/product-page/product-details.scss
> -            .pacing-faq-link {
This class is used on the program info box.

2024-04-30 17:24 UTC, collinpreston approved these changes

2024-04-30 18:04 UTC, merged