Add get_dated_courseruns function for availability to check for dated courses
mitodl/mitxonline pull request #2354
Opened 2024-08-21 18:10 UTC by JenniWhitman

### What are the relevant tickets?
Fixes https://github.com/mitodl/hq/issues/5260

### Description (What does it do?)
Rather than relying on the adverse, this PR adds a gunction, get_dated_courseruns, to get any dated, enrollable courseruns for the course being serialized.  I've also added a test to this effect. This will generate the correct availability as we defined dated as having 1 or more dated courseruns, regardless of whether they also had archived or self-paced courses.

### How can this be tested?
Create courseruns that are both enrollable and not, self-paced and not and you should still see dated as long as one is both enrollable and not self-paced.

2024-08-21 21:03 UTC, annagav requested changes
So that we not writing many filters over and over let's reuse the enrollable run filter.

2024-08-21 21:03 UTC, annagav commented on courses/utils.py
> +    return queryset.filter(
could we just call `get_enrollable_courseruns_qs` and then add two requirements: (is_self_paced=False) and (enrollment_end__isnull=True).

2024-08-22 18:59 UTC, cp-at-mit approved these changes

2024-08-22 19:01 UTC, annagav approved these changes

2024-08-22 19:01 UTC, merged