formatted course name and ordered them in explorer
mitodl/mitxonline pull request #336
Opened 2021-12-14 20:26 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
   - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes 322

#### What's this PR do?
This PR  accomplishes the following
- Changes the display name to `{courseReadableId} | {courseTitle}` 
- Sorts the title Alphabetically

#### How should this be manually tested?
This PR can be tested by the following
- Add courses to CMS
- Verify courses title is formatted correctly 
- Verify courses are sorted properly on Explorer Page

#### Screenshots (if appropriate)

Screenshots

<img width="1210" alt="Screenshot 2021-12-15 at 12 05 37 AM" src="https://user-images.githubusercontent.com/87968618/146074135-06295496-845b-4bbf-aee2-fcdf9aaf9ae1.png">

<img width="1210" alt="Screenshot 2021-12-15 at 12 05 28 AM" src="https://user-images.githubusercontent.com/87968618/146074295-1e1cd22b-2530-44e5-8738-cdbb8f76fe34.png">

2021-12-14 20:34 UTC, Wassaf-Shahzad commented
Hey, @briangrossman I went over the PR and have completed most of the tasks but I don't think there  is away to properly sort the courses in the navigation menu as explained in this thread
- https://github.com/wagtail/wagtail/issues/882.

2021-12-15 11:12 UTC, Wassaf-Shahzad commented
> Hey, @briangrossman I went over the PR and have completed most of the tasks but I don't think there is away to properly sort the courses in the navigation menu as explained in this thread
> 
> * [Configurable default sort order in the Explorer? wagtail/wagtail#882](https://github.com/wagtail/wagtail/issues/882).

Added wagtail hooks and added default sort order.

2021-12-16 13:28 UTC, arslanashraf7 requested changes
I added a few comments, let me know if you'd like to discuss.

2021-12-16 13:28 UTC, arslanashraf7 commented on cms/models.py
> +        return f"{self.course.readable_id} | {self.course.title}"
This thing is already being done in the course object str formatting, https://github.com/mitodl/mitxonline/blob/main/courses/models.py#L133. I think we can reuse that.

2021-12-16 13:28 UTC, arslanashraf7 commented on cms/wagtail_hooks.py
> +)
I don't think we need to define 3 different constant values without a possible reuseability, Probably having just one `DEFAULT_ORDER` seems fine and you can set the other values inside it.
 Also could you rename `DEFAULT_ORDER` to something like `DEFAULT_COURSE_LIST_ORDER`?

2021-12-16 13:28 UTC, arslanashraf7 commented on cms/wagtail_hooks.py
> +    if "ord" in param:
I couldn't really get the difference b/w `ord` & `[param]` on line#22. Could you add a little description of what's happening? This function should have some docstrings.

2021-12-20 13:18 UTC, arslanashraf7 approved these changes
Looks good 👍 Just a few minor comment, Feel free to merge once they are addressed.

2021-12-20 13:18 UTC, arslanashraf7 commented on cms/models.py
> +        """Gets the title of the course in the speacified format"""
```suggestion
        """Gets the title of the course in the specified format"""
```

2021-12-20 13:18 UTC, arslanashraf7 commented on cms/wagtail_hooks.py
> +    """Sort all pages by title alphabetically if no ordering is speacified"""
```suggestion
    """Sort all pages by title alphabetically if no ordering is specified"""
```

2021-12-20 13:18 UTC, arslanashraf7 commented on cms/wagtail_hooks.py
> +    """Swap admin pages API for our own flavor that orders results by title"""
```suggestion
    """Swap admin pages API for our own flavor that orders result by title"""
```

2021-12-20 14:07 UTC, briangrossman commented
@Wassaf-Shahzad - Screenshots LGTM, BTW

2021-12-20 14:51 UTC, merged