Implement resource pages and links from site footer
mitodl/mitxonline pull request #36
Opened 2021-07-27 12:21 UTC by umarmughal824

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
fixes #19 

#### What's this PR do?
Implement resource pages and links from site footer

#### How should this be manually tested?
Run the migrate command and then configure_wagtail that should populate three page Resource pages (Terms of Service / Honor Code / Privacy Policy)

#### Screenshots (if appropriate)
(Optional)

2021-07-27 12:42 UTC, umarmughal824 commented
@pdpinch could you please review the attached screenshots in the PR description.

2021-07-27 13:07 UTC, pdpinch commented
Why are there double-colons `::` in the mobile screenshots? 

Everything else seems fine. Please have someone from Arbisoft / Edly do a code review.

2021-07-27 13:42 UTC, umarmughal824 commented
> Why are there double-colons `::` in the mobile screenshots?

@pdpinch that's because I have added extra `:` in the content on the wagtail page title section.

I will get it reviewed once I will be done with the test cases.

2021-07-28 21:30 UTC, pdpinch commented
Can you add some `help_text` for the CMS user with the ideal image dimensions? on xPRO we found that CMS users were uploading much larger images than they needed to, which was bringing down our Lighthouse score.

2021-08-02 06:03 UTC, gsidebo requested changes

2021-08-02 06:03 UTC, gsidebo commented on cms/api.py
> +def create_resource_page_under_parent(title, parent):
```suggestion
def get_or_create_resource_page(title, parent):
```

2021-08-02 06:03 UTC, gsidebo commented on cms/api.py
> +    create_resource_page_under_parent("Honor Code", home_page)
Kwargs would make these a little clearer:

`get_or_create_resource_page("About Us", parent=home_page)`

2021-08-02 06:03 UTC, gsidebo commented on cms/models.py
> +    Basic resource page for all resource page.
```suggestion
    Basic resource page class for pages containing basic information (FAQ, etc.)
```

2021-08-02 22:32 UTC, gsidebo approved these changes
There are some ways that we should update this to match the designs more closely, but we have a bunch of open PRs and it's much better to merge this as it is now, then create a separate issue for the updates. LGTM! 👍

2021-08-03 09:14 UTC, merged

2021-08-03 09:16 UTC, umarmughal824 commented
> There are some ways that we should update this to match the designs more closely, but we have a bunch of open PRs and it's much better to merge this as it is now, then create a separate issue for the updates. LGTM! 👍

@gsidebo As I could not see the design for resource pages on invision so I can't say anything about it. If you have anything in mind that requires updates so please create an issue for that with the details.

2021-08-05 17:19 UTC, briangrossman commented
Tested it out on RC. Looks good! 👍 

- [About Us](https://mitxonline-rc.mitxonline.mit.edu/about-us/)
- [Terms of Service](https://mitxonline-rc.mitxonline.mit.edu/terms-of-service/)
- [Privacy Policy](https://mitxonline-rc.mitxonline.mit.edu/privacy-policy/)
- [Honor Code](https://mitxonline-rc.mitxonline.mit.edu/honor-code/)

Checking the box on the release...

2021-08-18 19:48 UTC, briangrossman commented
FYI: Updated these pages to include the content from xPRO. 

I changed every `MIT xPRO` => `MITx Online`. They will require a review to check for content problems. In particular, links and emails should be checked / updated. 

Of note:, xPRO has a `Subheading` at the top of each of these pages
![image](https://user-images.githubusercontent.com/21342568/129962507-24fd88cb-4d5a-4f99-b116-e633abd08fba.png)

... but MITx Online has a `Header Image` instead.
![image](https://user-images.githubusercontent.com/21342568/129962579-f8e67d4d-0dc3-45b3-970d-f81676575257.png)