Fix: forgot password regex failure fix and error message display
mitodl/mitxonline pull request #44
Opened 2021-07-30 11:34 UTC by arslanashraf7

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
#39 

#### What's this PR do?
- Updates the forgot-password API URL to match a regex of accurate length as of Django3
- Adds an error message for the user in case the API fails

#### How should this be manually tested?
- Setup, make sure the Django version is above 3 and visit `signin/forgot-password/`.
- Add dummy MAILGUN keys which will make the email API fail or forcefully throw an error from mail/API.
- Make sure that an error message is shown to the user
- Now configure the right MAILGUN creds and visit `signin/forgot-password/`
- Make sure that the user is able to reset the password correctly

#### Where should the reviewer start?
- Probably run an instance and verify the generated token length as mentioned in [here](https://github.com/mitodl/mitxonline/issues/39#issuecomment-889822686)
- Now, run this PR and make sure that the acceptance criteria mention in the ticket is met. 

#### Screenshots (if appropriate)
(Optional)

2021-07-30 11:51 UTC, pdpinch commented
Seems like we should add some unit tests to avoid this problem in the future? I'd like to get this merged ASAP, so if the tests can't be added today, I'd be fine with opening an issue to follow up with it later.

2021-07-30 11:52 UTC, pdpinch commented
@rhysyngsun is this something we need to update in https://github.com/mitodl/ol-django/ ?

2021-07-30 13:02 UTC, arslanashraf7 commented
@pdpinch Could you please take a look at the screenshots and let me know if they are fine by you.

>Seems like we should add some unit tests to avoid this problem in the future? I'd like to get this merged ASAP, so if the tests can't be added today, I'd be fine with opening an issue to follow up with it later.

I've added some tests for the backend. For the frontend, I'll try to add some today otherwise I'll create a ticket for that and get to it later.

2021-07-30 13:05 UTC, pdpinch commented
> Could you please take a look at the screenshots and let me know if they are fine by you.

Thanks. Screenshots look OK. The line breaks are awkward, but I don't want to worry about that. 

And thanks for the tests.

2021-08-02 20:35 UTC, rhysyngsun requested changes
I got this error when trying to reset my password:
```
web_1     | [2021-08-02 20:32:39] ERROR 10 [django.request] log.py:224 - [dd0950ebd771] - Internal Server Error: /signin/forgot-password/confirm/MQ/aqrszo-07cc9d6806003c19caf9ca43fbc7cdc8/
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1     |     response = get_response(request)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
web_1     |     return callback(request, *args, **kwargs)
web_1     | TypeError: index() got an unexpected keyword argument 'uid'
```

2021-08-02 20:35 UTC, rhysyngsun commented on mail/api.py
> +            log.exception(
`log.exception()` shouldn't be called outside of a `try ... except ...` block
```suggestion
            log.error(
```

2021-08-04 15:01 UTC, rhysyngsun approved these changes

2021-08-04 15:38 UTC, merged