Adding Discount UI
mitodl/mitxonline pull request #444
Opened 2022-02-25 20:42 UTC by jkachel

#### Pre-Flight checklist

- [X] Screenshots and design review for any changes that affect layout or styling
  - [X] Desktop screenshots
  - [X] Mobile width screenshots
- [X] Migrations
  - [X] Migration is backwards-compatible with current production code
- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested
- [x] Settings
  - [ ] New settings are documented and present in `app.json`
  - [X] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
Fixes #431

#### What's this PR do?
Adds support for discount redemption:
* Adds UI to apply and clear discount codes
* Updates backend APIs to handle discount code redemption following the established rules
* Updates the Django Admin to include screens for discount redemptions, and to display discounts applied on each order.

#### How should this be manually tested?
Ensure your setup has a valid product and course combination set up. 
Add a discount code in via djadmin and note the code you create.
Add a product to your cart, and then apply the discount code using the form in Order Summary.
The discount should be applied successfully and the price should reflect the discounted amount.

To test adding multiple codes to an order: follow the same instructions as above but add more than one discount. Then, apply a discount code after applying a discount code. The new code should take precedence over the old one.

To test user discounts: follow the first two steps under the standard test, then also add a User Discount record. Log in as the user you added the discount for and add a product to the cart. You should see that the discount has been applied to the cart automatically. Applying another discount over the user discount should override the user discount, but clearing the discount should re-apply the user discount. Other accounts in the system should not have the discount applied to their carts automatically. 

#### Any background context you want to provide?
Rules as follows:
- Only a single discount can be applied to a given cart - any additional discounts added after the first override the last added discount. 
- User discounts are always applied, unless overridden by another discount.
- Discounts that have hit the maximum number of redemptions (either by hitting the value in max_redemptions, or by virtue of being a "one-time" or "one-time-per-user" discount type) will return a "not found" and won't be applied. 
- Discounts are applied to the total amount in the cart (there's only one allowed item in the cart right now, though)

Also of note:
- Error and success states right now pop a standard banner notification. This wasn't in the InVision mockup - seemed reasonable so included it. 
- The "Adding another discount" text disappears if there's not already a discount applied.
- Clear Discount only appears if there's a discount to clear. The front-end has no idea (right now) if a discount is a user discount or not so you can clear a user discount; it just won't apparently do anything as the discount will just get reapplied. 
- Fixed Price discounts probably need some styling help - I added Fixed Price text in there to differentiate them from the dollar off or percent off discounts. Input appreciated for this. 

#### Screenshots (if appropriate)
Desktop:
![Screen Shot 2022-02-25 at 2 25 00 PM](https://user-images.githubusercontent.com/945611/155799877-16eb64ee-44dc-4856-838a-0e5e6571cc98.png)
![Screen Shot 2022-02-25 at 2 25 34 PM](https://user-images.githubusercontent.com/945611/155799880-54b2f09e-1cfe-4b3c-aad6-4d8ffb1651e6.png)
![Screen Shot 2022-02-25 at 2 26 07 PM](https://user-images.githubusercontent.com/945611/155799882-8c7dc97c-0a84-46e0-a8c9-118561b97136.png)

Mobile:
![Screen Shot 2022-02-25 at 2 25 18 PM](https://user-images.githubusercontent.com/945611/155799879-d4a8d172-ab51-4cea-b521-a139bf5e1898.png)
![Screen Shot 2022-02-25 at 2 25 27 PM](https://user-images.githubusercontent.com/945611/155799905-5f856f7e-5bc5-46dd-80c7-1ade5750d8ee.png)
![Screen Shot 2022-02-25 at 2 26 11 PM](https://user-images.githubusercontent.com/945611/155799907-c1aafb17-f6ec-4189-ae15-5abc9d90c6f7.png)

2022-03-04 19:25 UTC, rhysyngsun requested changes
Code review

2022-03-04 19:25 UTC, rhysyngsun commented on ecommerce/models.py
> +        redemption = DiscountRedemption(
Would it be safer to do a `get_or_create` on this to make it idempotent?

2022-03-04 19:25 UTC, rhysyngsun commented on ecommerce/discounts_test.py
> +    assert onetime_discount.check_validity(user) == True
Assertions against singletons like `True` and `False` should be done with `is`:
```suggestion
    assert onetime_discount.check_validity(user) is True
```

Same for similar usages in this file.

2022-03-04 19:25 UTC, rhysyngsun commented on ecommerce/discounts_test.py
> +def test_one_time_discount(user, onetime_discount):
These tests for model methods should probably live in a `models_test.py` file instead.

2022-03-07 18:31 UTC, jkachel commented
https://github.com/mitodl/mitxonline/pull/444/commits/68b5c4546671ef03019856f0c41bd18ac710feb4 should handle all the comments from Friday (3/4).

2022-03-07 22:23 UTC, rhysyngsun requested changes
I'm getting stuck on this error when checking out:

```
web_1     | [2022-03-07 22:15:10] ERROR 13 [django.request] log.py:224 - [39ff2ccd9958] - Internal Server Error: /checkout/to_payment
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1     |     response = get_response(request)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
web_1     |     return callback(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
web_1     |     return self.dispatch(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
web_1     |     return super().dispatch(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
web_1     |     return handler(request, *args, **kwargs)
web_1     |   File "/src/./ecommerce/views/v0/__init__.py", line 474, in get
web_1     |     checkout_payload = api.generate_checkout_payload(request)
web_1     |   File "/src/./ecommerce/api.py", line 19, in generate_checkout_payload
web_1     |     order = PendingOrder.create_from_basket(basket)
web_1     |   File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
web_1     |     return func(*args, **kwds)
web_1     |   File "/src/./ecommerce/models.py", line 273, in create_from_basket
web_1     |     total += line.discounted_price
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
web_1     |     res = instance.__dict__[self.name] = self.func(instance)
web_1     |   File "/src/./ecommerce/models.py", line 432, in discounted_price
web_1     |     DiscountType.get_discounted_price(
web_1     |   File "/src/./ecommerce/discounts.py", line 77, in get_discounted_price
web_1     |     discount_cls = DiscountType.for_discount(discount)
web_1     |   File "/src/./ecommerce/discounts.py", line 61, in for_discount
web_1     |     DiscountTypeCls = cls._CLASSES[discount.discount_type]
web_1     | AttributeError: 'DiscountRedemption' object has no attribute 'discount_type'
```

I think this is because my suggestion [here]() wasn't correct and that it needs to step into `DiscountRedemption.redeemed_discount`.

2022-03-07 22:23 UTC, rhysyngsun commented on static/js/containers/pages/checkout/CartPage.js
> +    })
I think it's fine to just drop this, it shifts the page layout, which is a bit distracting and there's already an inline error message.

2022-03-08 15:37 UTC, rhysyngsun approved these changes

2022-03-08 15:49 UTC, merged