Adding OrderReceiptPage
mitodl/mitxonline pull request #449
Opened 2022-03-02 14:17 UTC by annagav

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
Fix #424

#### What's this PR do?
Add an order receipts page

#### How should this be manually tested?
TBA

2022-03-09 17:00 UTC, rhysyngsun commented
>     2. Do we want to be able to reach the receipt page for a given order directly? This may be a better question for @rhysyngsun (and may be outside the scope of this request).

Yes, the receipt page should have a navigable url.

2022-03-14 12:37 UTC, jkachel commented on static/js/containers/pages/checkout/OrderReceiptPage.js
> +    const totalPaid = parseFloat(orderReceipt.total_price_paid)
This needs a check for null - it fails for me consistently.

2022-03-14 12:51 UTC, jkachel commented on static/js/components/OrderSummaryCard.js
> +        {!SETTINGS.features.disable_discount_ui && !orderFulfilled && discountCode ? (
The discountCode check here prevents ApplyCouponForm from rendering.

2022-03-14 16:21 UTC, annagav commented
@jkachel I addressed all the comments. Thank you

2022-03-14 18:50 UTC, jkachel requested changes
Couple more small things

2022-03-14 18:50 UTC, jkachel commented on static/js/containers/pages/checkout/OrderReceiptPage.js
> +  isLoading:    pathOr(true, ["queries", "orderReceipt", "isPending"], state)
"orderReceipt" here should be the receiptQueryKey

2022-03-14 18:50 UTC, jkachel commented on static/js/components/OrderSummaryCard.js
> +    const discountAmount = Number(discounts[0].amount)
discounts[x] has a "redeemed_discount" key - as is this renders as NaN (and also has problems on line 32 and 58)

2022-03-14 19:53 UTC, annagav commented
@jkachel I addressed your comments. I think it is ready for review again

2022-03-14 20:28 UTC, jkachel approved these changes
LGTM 👍

2022-03-14 20:49 UTC, merged