Adds flexible pricing form
mitodl/mitxonline pull request #553
Opened 2022-05-06 20:06 UTC by jkachel

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [X] Migrations
  - [X] Migration is backwards-compatible with current production code
- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested

#### What are the relevant tickets?
#539 

#### What's this PR do?
Implements #539: Adds a Flexible Pricing Request Form to the available Wagtail forms.

Within the CMS, the form has customizable blocks for intro text and post-submit text, text for guest users, and text for  application in progress, application approved, and application denied states. Admins can customize the form fields, but the form must contain a Your Income and Income Currency field to capture the user's yearly income (similar to the form on MicroMasters). Upon submission, the form submission also creates a FlexiblePrice record, which can be used to track processing of the request. 

Applicants must be logged in to access the form - otherwise, the Guest User text is displayed and the user cannot submit an application. They must not have a prior submission. Applicants with a submission will see the appropriate text for the status of their submission (in progress, approved, skipped). 

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

2022-05-16 13:30 UTC, pdpinch commented
The submission response should be conditional on whether the request is automatically accepted, or needs review. 

If it needs review, we need to offer a link to docusign for the learner to upload documents for review.

2022-05-16 19:03 UTC, jkachel commented
> The submission response should be conditional on whether the request is automatically accepted, or needs review.
> 
> If it needs review, we need to offer a link to docusign for the learner to upload documents for review.

@pdpinch Would the DocuSign location be specific to the learner? (In other words, does the code need to generate a location for the learner's documentation via API or can someone just put a link to a submit form into a text box in Wagtail?)

2022-05-17 19:52 UTC, annagav requested changes

2022-05-17 19:52 UTC, annagav commented on cms/models.py
> +class FlexiblePricingFormBuilder(FormBuilder):
could you add a docstring

2022-05-17 19:52 UTC, annagav commented on cms/models.py
> +class FormField(AbstractFormField):
could you add a docstring

2022-05-17 19:52 UTC, annagav commented on cms/models.py
> +class FlexiblePricingRequestForm(AbstractForm):
could you add a docstring here as well

2022-05-17 19:52 UTC, annagav commented on cms/models.py
> +    def get_template(self, request, *args, **kwargs):
I think the template name is already all set from this line `template_name = "flexiblepricing/flexible_pricing_request_form.html"`.  It seems that the method is only useful if you want to change the template dynamically.

2022-05-18 17:02 UTC, pdpinch commented
> Would the DocuSign location be specific to the learner? 

No. It's a fixed URL for all users. You can see how it works on micromasters: 

https://github.com/mitodl/micromasters/blob/7bb555db606da884dece82ba2d00010fe949ce7b/static/js/components/dashboard/FinancialAidCard.js#L205

2022-05-18 19:37 UTC, jkachel commented
https://github.com/mitodl/mitxonline/pull/553/commits/e0cdd101e48d42e507004a046a8fba54adb7f3ec adds a landing page template that can be displayed after the form is submitted that contains the DocuSign link and manual submission address. The commit doesn't include logic for displaying that particular template if the request won't be auto approved, since that'll be covered in https://github.com/mitodl/mitxonline/issues/542 (currently assigned to @asadiqbal08).

2022-05-19 19:24 UTC, jkachel commented
@annagav resolved merge conflict

2022-05-19 20:55 UTC, annagav commented
@jkachel the fields are not showing up for me:
<img width="1481" alt="Screen Shot 2022-05-19 at 4 55 16 PM" src="https://user-images.githubusercontent.com/7574259/169403140-a4565eba-f720-41f0-8186-834d6fab26f7.png">

2022-05-19 21:48 UTC, annagav requested changes
Should we add to REDME an instruction for how to set it up if you a course admin?

2022-05-20 12:19 UTC, jkachel commented
@annagav I can't tell from the screenshot - are you maybe seeing the status display instead of the form? If there's a submission for the user in there, it won't display the form. 

Adding a README is a good idea; I'll put one in the docs.

2022-05-20 13:40 UTC, annagav commented
@jkachel I am getting error on form submission:
<img width="731" alt="Screen Shot 2022-05-20 at 9 39 09 AM" src="https://user-images.githubusercontent.com/7574259/169540349-2e934ec5-9e13-4459-b913-a1fdb3671f2d.png">

2022-05-20 13:55 UTC, jkachel commented
@annagav do you have an Income Currency field in your form? It's a requirement.

2022-05-20 16:41 UTC, annagav requested changes
After I was able to submit the form successfully, I got the "thank you for submission" message, I was thinking maybe if I refresh the page I'll get the status of my application. But then on each refresh of the page I created duplicate submissions.

2022-05-23 15:54 UTC, annagav approved these changes
👍

2022-05-23 16:16 UTC, merged