Adds username normalization
mitodl/mitxonline pull request #627
Opened 2022-06-15 20:51 UTC by jkachel

#### Pre-Flight checklist

- [X] Migrations
  - [X] Migration is backwards-compatible with current production code
- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested

#### What are the relevant tickets?

#259 

#### What's this PR do?

Fixes #259.

This adds a `normalized_username` field to the users model and an API function to perform the normalization. It also updates the openedx `create_edx_user` call to pass the `normalized_username` field instead of the regular `username` field. 

#### How should this be manually tested?

The migrations to add the `normalized_username` field will automatically normalize the usernames. Because of that, it's pretty important that your user database does not contain accounts that will conflict. (Per #259, the `normalized_username` field is uniqued.) There is a management command to check for and fix usernames that would conflict that's in PR XXX _(todo: this PR)_.

After performing the migrations, create a user with a username using accented characters (áüô, etc.). The username should be created on the Open edX side with those characters converted to non-accented characters (auo, etc.). 

Some characters will _not_ be normalized and will instead be dropped. This includes ø so testing with that character will result in a normalized username without that character (for example, Søren will normalize to Sren).

2022-06-22 12:59 UTC, annagav requested changes
Just a minor comment

2022-06-22 12:59 UTC, annagav commented on users/models_test.py
> +def test_username_normalization():
Is this a duplicate of the test in the api.py? Is this test incomplete?

2022-06-23 12:51 UTC, annagav approved these changes
👍

2022-11-02 20:43 UTC, pdpinch commented
@jkachel can you remind me why you put this on hold?

Would this have avoided the situation in https://odl.zendesk.com/agent/tickets/139242 and https://sentry.io/organizations/mit-office-of-digital-learning/issues/2616447470/events/9ab540c0d80f4983933e71bb7b9cd728/?project=5864687

2022-11-02 21:07 UTC, jkachel commented
> @jkachel can you remind me why you put this on hold?
> 
> Would this have avoided the situation in https://odl.zendesk.com/agent/tickets/139242 and https://sentry.io/organizations/mit-office-of-digital-learning/issues/2616447470/events/9ab540c0d80f4983933e71bb7b9cd728/?project=5864687

This was put on hold because it needed some coordination to do - there was a part to this that was normalizing the existing usernames in the database. (See https://github.com/mitodl/mitxonline/issues/259#issuecomment-946706104) This was done about the time Brian left, though; I was going to get him to help with that. Otherwise, the code worked and it would have caught this, I think. It'd need some revising to work in the current version of the app before we could deploy it now.

2025-01-03 19:19 UTC, pdpinch commented
@jkachel doesn't look like we're going to get back to this anytime soon. Can we close this PR? 

I'm not even sure it would still be relevant once we move to keycloak SSO

2025-01-03 19:23 UTC, jkachel commented
> @jkachel doesn't look like we're going to get back to this anytime soon. Can we close this PR?

Oh wow, I forgot this was out there. This will definitely get superseded by the Keycloak integration, so closing it.

2025-01-03 19:23 UTC, closed without merging