Flexible Pricing: approved requests should apply to programs
mitodl/mitxonline pull request #682
Opened 2022-07-11 19:35 UTC by jkachel

#### Pre-Flight checklist

- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested

#### What are the relevant tickets?

#678

#### What's this PR do?

Partially implements #678 - updates the flexible pricing application code to consider programs along with courses. If the course belongs to a program, or the request is tied to a program, the application code will look for tiers that apply to the program. 

#### How should this be manually tested?

Automated tests should pass.
Flexible Pricing requests for an individual, standalone course should work. If the course is manually added to a program (e.g. via Django Admin), the tiers that are set up for the program should take precedence over the tiers for the course and you should see those discounts when you check out. (You can't buy enrollment in a program at this point so testing tier application through the frontend for a program won't work just yet.)

2022-07-12 18:05 UTC, rhysyngsun requested changes

2022-07-12 19:23 UTC, jkachel commented on flexiblepricing/api.py
> +        )
Got both of these in https://github.com/mitodl/mitxonline/pull/682/commits/a85a28f93f77819eabd8c60e259b7091838c0ace .

2022-07-19 01:30 UTC, rhysyngsun approved these changes

2022-07-21 14:59 UTC, rhysyngsun approved these changes
LGTM :+1:

2022-07-22 12:15 UTC, merged