Refund order based on id or reference number
mitodl/mitxonline pull request #847
Opened 2022-08-15 18:06 UTC by annagav

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fix https://github.com/mitodl/mitxonline/issues/816

#### What's this PR do?
Refund order based on id or reference number

#### How should this be manually tested?
Try to refund an order through django admin, and through google sheets

2022-08-16 20:26 UTC, rhysyngsun requested changes
Code review, will do a functional test tomorrow morning.

2022-08-16 20:26 UTC, rhysyngsun commented on ecommerce/api.py
> +def refund_order(*, order_id: int = None, reference_number=None, **kwargs):
Could you type `reference_number` as a `str` in the signature?

2022-08-16 20:26 UTC, rhysyngsun commented on ecommerce/api.py
> +                f"Either order_id or reference_number is required to fetch the Order. "
Doesn't need to be an f-string and has an extra trailing space. This should also probably be an error.

2022-08-16 20:26 UTC, rhysyngsun commented on ecommerce/api.py
> +        order_recent_transaction = Transaction.objects.filter(order=order.id).first()
Nit: could be `order.transactions.first()`

2022-08-16 20:26 UTC, rhysyngsun commented on ecommerce/api.py
> +            log.debug(f"Order with order_id {order.id} is not in fulfilled state.")
For this and the other log strings, it should use `%s` formatting so they get deduplicated in sentry.

2022-08-16 20:26 UTC, rhysyngsun commented on ecommerce/api_test.py
> +    assert f"Either order_id or reference_number is required to fetch the Order."
Doesn't need to be an f-string.

2022-08-17 22:43 UTC, rhysyngsun requested changes
I'm getting this error trying to test, which I think needs to be fixed in the refunds library which is trying to parse the order id column as an int still:

```
[2022-08-17 22:41:01] ERROR 7 [mitol.google_sheets_refunds.api] api.py:61 - [d28c18aed9c6] - Parsing failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mitol/google_sheets_refunds/utils.py", line 79, in parse_raw_data
    order_id=int(raw_row_data[6]),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mitol/google_sheets_refunds/api.py", line 59, in process_row
    refund_req_row = RefundRequestRow.parse_raw_data(row_index, row_data)
  File "/usr/local/lib/python3.9/site-packages/mitol/google_sheets_refunds/utils.py", line 95, in parse_raw_data
    raise SheetRowParsingException(str(exc)) from exc
mitol.google_sheets.exceptions.SheetRowParsingException: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

2022-08-26 11:53 UTC, annagav commented
closed by accident

2022-08-31 02:37 UTC, rhysyngsun commented
@annagav I've cut a new release of mitol-django-common that should fix the test failure: https://pypi.org/project/mitol-django-common/2.5.2/

2022-09-06 03:35 UTC, rhysyngsun commented
@annagav I've been trying to test this but I'm finding that it's failing because my google sheet isn't copying over reference numbers - it's still copying over historical numeric order ids but not the ones with the prefix. Any ideas on why or what I need to fix?

2022-09-06 20:40 UTC, rhysyngsun commented on sheets/plugins.py
> +            reference_number=refund_request_row.order_id, unenroll=True
Needs to be fixed to use the new property:

```suggestion
            reference_number=refund_request_row.order_ref_num, unenroll=True
```

2022-09-07 13:22 UTC, rhysyngsun requested changes
I don't think you'd meant to change the other two files in your last commit.

2022-09-07 14:44 UTC, rhysyngsun approved these changes
:+1: when tests pass

2022-09-07 15:06 UTC, merged