Changes the receipt email subject
mitodl/mitxonline pull request #949
Opened 2022-09-08 16:18 UTC by jkachel

#### Pre-Flight checklist

- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested

#### What are the relevant tickets?

Fixes #945

#### What's this PR do?

Changes the email subject on the receipt emails to "MITx Online Receipt". 

#### How should this be manually tested?

Restart your environment (so the change gets picked up) and check out. The receipt email should be "MITx Online Receipt".

2022-09-08 16:34 UTC, pdpinch commented
Having 2nd thoughts about this text. Please don't merge until I've reviewed.

2022-09-13 06:16 UTC, asadali145 approved these changes
LGTM!

2022-09-16 06:26 UTC, asadali145 commented
@jkachel you can merge this one. Just a reminder in case you forgot to merge as it happened to me in past as well :)

2022-09-16 12:05 UTC, jkachel commented
@pdpinch are there changes that need to be made to the wording?

2022-09-24 20:43 UTC, pdpinch requested changes

2022-09-24 20:43 UTC, pdpinch commented on ecommerce/templates/mail/product_order_receipt/subject.txt
> +MITx Online Purchase
I looked through all the email receipts in my inbox, and this pattern seems most common:

```suggestion
Your receipt from MITx Online
```

If `MITx Online` is an available in an environment-specific setting string, we should use that. But not if it's more than 5m of effort.

2022-09-27 13:35 UTC, asadali145 approved these changes

2022-09-28 20:01 UTC, pdpinch approved these changes

2022-09-28 20:37 UTC, merged